os: osx
sudo: required
language: java
jdk: oraclejdk8
addons: 
  chrome: stable
  apt:
    packages:
    - realpath
    - xvfb
before_install:
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
 - if [ ! -d ~/chromedriver ]; then mkdir ~/macchromedriver; wget -N https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip -P ~/macchromedriver; yes | unzip ~/chromedriver/chromedriver_linux64.zip -d ~/macchromedriver; fi
 - chmod a+x /home/travis/macchromedriver/chromedriver
 - /home/travis/macchromedriver/chromedriver &
install:
 - pushd /tmp/WALA
 - mvn clean install -DskipTests -B -q
 - popd
script:
 - xvfb-run mvn clean install
sudo: false
cache:
  directories:
    - $HOME/.m2
