language: android
android:
  components:
    - build-tools-26.0.2
jdk: oraclejdk8
addons: 
  chrome: stable
  apt:
    packages:
    - realpath
    - xvfb
before_install:
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
 - if [ ! -d ~/linuxchromedriver ]; then mkdir ~/linuxchromedriver; wget -N https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip -P ~/linuxchromedriver; yes | unzip ~/linuxchromedriver/chromedriver_linux64.zip -d ~/linuxchromedriver; fi
 - chmod a+x /home/travis/linuxchromedriver/chromedriver
 - /home/travis/linuxchromedriver/chromedriver &
install:
 - pushd /tmp/WALA
 - mvn clean install -DskipTests -B -q
 - popd
script:
 - xvfb-run mvn clean install
sudo: false
cache:
  directories:
    - $HOME/.m2
